namespace :db do
  desc "Fill database with sample data"
  task populate: :environment do
    make_malts
    make_hops
    make_yeasts
    make_styles
  end
end

def make_malts
  Malt.create!(name: "2-row",
               potential: 1.037,
               malt_yield: 0.8,
               srm: 1.8,
               base_malt?: true)
  Malt.create!(name: "caramel 60",
               potential: 1.034,
               malt_yield: 0.73,
               srm: 60,
               base_malt?: false)
  Malt.create!(name: "chocolate",
               potential: 1.034,
               malt_yield: 0.75,
               srm: 350,
               base_malt?: false)
  Malt.create!(name: "pilsen",
               potential: 1.037,
               malt_yield: 0.8,
               srm: 1.0,
               base_malt?: true)
  Malt.create!(name: "maris otter",
               potential: 1.038,
               malt_yield: 0.82,
               srm: 3.0,
               base_malt?: true)
  Malt.create!(name: "honey malt",
               potential: 1.037,
               malt_yield: 0.8,
               srm: 25.0,
               base_malt?: false)
  Malt.create!(name: "white wheat",
               potential: 1.040,
               malt_yield: 0.86,
               srm: 2.4,
               base_malt?: true)
  Malt.create!(name: "biscuit",
               potential: 1.032,
               malt_yield: 0.70,
               srm: 23,
               base_malt?: false)
  Malt.create!(name: "brown malt",
               potential: 1.032,
               malt_yield: 0.70,
               srm: 65,
               base_malt?: false)
  Malt.create!(name: "black malt",
               potential: 1.025,
               malt_yield: 0.55,
               srm: 500,
               base_malt?: false)
  Malt.create!(name: "munich 10",
               potential: 1.035,
               malt_yield: 0.76,
               srm: 10,
               base_malt?: false)
  Malt.create!(name: "carafa I",
               potential: 1.032,
               malt_yield: 0.70,
               srm: 337,
               base_malt?: false)
  Malt.create!(name: "caramel 20",
               potential: 1.034,
               malt_yield: 0.73,
               srm: 20,
               base_malt?: false)
  Malt.create!(name: "rye malt",
               potential: 1.029,
               malt_yield: 0.63,
               srm: 4.7,
               base_malt?: false)
  Malt.create!(name: "vienna",
               potential: 1.036,
               malt_yield: 0.77,
               srm: 3.5,
               base_malt?: true)
    Malt.create!(name: "special B",
               potential: 1.030,
               malt_yield: 0.65,
               srm: 150,
               base_malt?: false)
    Malt.create!(name: "candi sugar",
               potential: 1.046,
               malt_yield: 1.00,
               srm: 2,
               base_malt?: false)
    Malt.create!(name: "honey",
               potential: 1.034,
               malt_yield: 0.75,
               srm: 1,
               base_malt?: false)
    Malt.create!(name: "special roast",
               potential: 1.033,
               malt_yield: 0.72,
               srm: 50,
               base_malt?: false)
end

def make_hops
  Hop.create!(name: "cascade",
              alpha: 5.5)
  Hop.create!(name: "centennial",
              alpha: 10.0)
  Hop.create!(name: "hallertau",
              alpha: 4.8)
  Hop.create!(name: "citra",
              alpha: 12.0)
  Hop.create!(name: "east kent goldings",
              alpha: 5.0)
  Hop.create!(name: "saaz",
              alpha: 3.75)
  Hop.create!(name: "amarillo",
              alpha: 9.0)
  Hop.create!(name: "willamette",
              alpha: 5.5)
  Hop.create!(name: "tettnang",
              alpha: 4.5)
  Hop.create!(name: "spalt",
              alpha: 4.5)
  Hop.create!(name: "simcoe",
              alpha: 13)
  Hop.create!(name: "fuggle",
              alpha: 4.5)
  Hop.create!(name: "sorachi ace",
              alpha: 13.0)
end

def make_yeasts
  Yeast.create!(name: "WY1007",
                attenuation: 76,
                family: "german ale")
  Yeast.create!(name: "WY1056",
                attenuation: 75,
                family: "ale")
  Yeast.create!(name: "WY1098",
                attenuation: 72,
                family: "ale")
  Yeast.create!(name: "WLP090",
                attenuation: 80,
                family: "ale")
  Yeast.create!(name: "WY2007",
                attenuation: 73,
                family: "lager")
  Yeast.create!(name: "WY1099",
                attenuation: 70,
                family: "ale")
  Yeast.create!(name: "WY3056",
                attenuation: 75,
                family: "wheat")
  Yeast.create!(name: "WY2001",
                attenuation: 74,
                family: "lager")
  Yeast.create!(name: "WY1214",
                attenuation: 76,
                family: "belgian")
  Yeast.create!(name: "WY3944",
                attenuation: 74,
                family: "belgian")
  Yeast.create!(name: "WY3711",
                attenuation: 80,
                family: "saison")
  Yeast.create!(name: "WY3522",
                attenuation: 74,
                family: "belgian")
  Yeast.create!(name: "WY3724",
                attenuation: 78,
                family: "saison")
  Yeast.create!(name: "WY2565",
                attenuation: 75,
                family: "kolsch")
end

def make_styles
  Style.create!(name: "American IPA",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["2-row"],
                common_hops: ["cascade", "citra"],
                aroma_required?: true,
                abv_upper: 7.5,
                abv_lower: 5.5,
                ibu_upper: 70,
                ibu_lower: 40,
                srm_upper: 15,
                srm_lower: 6)
  Style.create!(name: "American Stout",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["chocolate"],
                common_hops: nil,
                aroma_required?: false,
                abv_upper: 7,
                abv_lower: 5,
                ibu_upper: 75,
                ibu_lower: 35,
                srm_upper: 40,
                srm_lower: 30)
  Style.create!(name: "Pilsner",
                yeast_family: "lager",
                required_malts: ["pilsen"],
                required_hops: nil,
                common_malts: nil,
                common_hops: ["hallertau", "spalt", "tettnang", "saaz"],
                aroma_required?: false,
                abv_upper: 5.2,
                abv_lower: 4.4,
                ibu_upper: 45,
                ibu_lower: 25,
                srm_upper: 2,
                srm_lower: 5)
  Style.create!(name: "American Pale",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["2-row"],
                common_hops: ["centennial", "simcoe"],
                aroma_required?: false,
                abv_upper: 6.2,
                abv_lower: 4.5,
                ibu_upper: 45,
                ibu_lower: 30,
                srm_upper: 14,
                srm_lower: 5)
  Style.create!(name: "Imperial Stout",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["chocolate"],
                common_hops: nil,
                aroma_required?: false,
                abv_upper: 12.0,
                abv_lower: 8.0,
                ibu_upper: 90,
                ibu_lower: 50,
                srm_upper: 40,
                srm_lower: 30)
  Style.create!(name: "Red Ale",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["maris otter"],
                common_hops: ["east kent goldings", "fuggle"],
                aroma_required?: false,
                abv_upper: 6.0,
                abv_lower: 4.0,
                ibu_upper: 28,
                ibu_lower: 17,
                srm_upper: 18,
                srm_lower: 9)
  Style.create!(name: "Weizen",
                yeast_family: "wheat",
                required_malts: ["white wheat"],
                required_hops: nil,
                common_malts: ["pilsen"],
                common_hops: ["hallertau", "saaz", "tettnang", "spalt", "saaz"],
                aroma_required?: false,
                abv_upper: 5.6,
                abv_lower: 4.3,
                ibu_upper: 15,
                ibu_lower: 8,
                srm_upper: 8,
                srm_lower: 2)
  Style.create!(name: "Imperial IPA",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["2-row"],
                common_hops: ["cascade", "simcoe"],
                aroma_required?: true,
                abv_upper: 12.0,
                abv_lower: 7.5,
                ibu_upper: 130,
                ibu_lower: 60,
                srm_upper: 15,
                srm_lower: 8)
  Style.create!(name: "Session IPA",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["2-row"],
                common_hops: ["amarillo"],
                aroma_required?: true,
                abv_upper: 4.8,
                abv_lower: 3.5,
                ibu_upper: 50,
                ibu_lower: 35,
                srm_upper: 12,
                srm_lower: 3)
  Style.create!(name: "Brown Porter",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["brown malt", "maris otter"],
                common_hops: ["east kent goldings", "fuggle"],
                aroma_required?: false,
                abv_upper: 5.4,
                abv_lower: 4,
                ibu_upper: 35,
                ibu_lower: 18,
                srm_upper: 30,
                srm_lower: 20)
  Style.create!(name: "Robust Porter",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["black malt"],
                common_hops: nil,
                aroma_required?: false,
                abv_upper: 6.5,
                abv_lower: 4.8,
                ibu_upper: 50,
                ibu_lower: 25,
                srm_upper: 35,
                srm_lower: 22)
  Style.create!(name: "Schwarzbier",
                yeast_family: "lager",
                required_malts: ["pilsen"],
                required_hops: nil,
                common_malts: ["munich 10", "carafa I"],
                common_hops: nil,
                aroma_required?: false,
                abv_upper: 5.4,
                abv_lower: 4.4,
                ibu_upper: 32,
                ibu_lower: 22,
                srm_upper: 30,
                srm_lower: 17)
  Style.create!(name: "Dunkelweizen",
                yeast_family: "wheat",
                required_malts: ["white wheat"],
                required_hops: nil,
                common_malts: ["munich 10"],
                common_hops: ["hallertau", "spalt", "tettnang", "saaz"],
                aroma_required?: false,
                abv_upper: 5.6,
                abv_lower: 4.3,
                ibu_upper: 18,
                ibu_lower: 10,
                srm_upper: 23,
                srm_lower: 10)
  Style.create!(name: "American Wheat",
                yeast_family: "ale",
                required_malts: ["white wheat"],
                required_hops: nil,
                common_malts: ["2-row"],
                common_hops: ["amarillo", "cascade", "centennial"],
                aroma_required?: false,
                abv_upper: 5.5,
                abv_lower: 4.0,
                ibu_upper: 30,
                ibu_lower: 15,
                srm_upper: 6,
                srm_lower: 3)
  Style.create!(name: "Wheat Wine",
                yeast_family: "ale",
                required_malts: ["white wheat"],
                required_hops: nil,
                common_malts: ["caramel 60"],
                common_hops: nil,
                aroma_required?: false,
                abv_upper: 9.6,
                abv_lower: 6.7,
                ibu_upper: 85,
                ibu_lower: 50,
                srm_upper: 15,
                srm_lower: 8)
  Style.create!(name: "Bock",
                yeast_family: "lager",
                required_malts: ["vienna"],
                required_hops: nil,
                common_malts: ["munich 10"],
                common_hops: ["hallertau", "tettnang", "spalt", "saaz"],
                aroma_required?: false,
                abv_upper: 7.2,
                abv_lower: 6.3,
                ibu_upper: 27,
                ibu_lower: 20,
                srm_upper: 22,
                srm_lower: 14)
  Style.create!(name: "Alt",
                yeast_family: "german ale",
                required_malts: ["pilsen"],
                required_hops: nil,
                common_malts: ["munich 10", "vienna"],
                common_hops: ["hallertau", "tettnang", "spalt", "saaz"],
                aroma_required?: false,
                abv_upper: 5.2,
                abv_lower: 4.5,
                ibu_upper: 50,
                ibu_lower: 25,
                srm_upper: 19,
                srm_lower: 11)
  Style.create!(name: "ESB",
                yeast_family: "ale",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["maris otter", "caramel 20", "caramel 60"],
                common_hops: ["east kent goldings", "fuggle"],
                aroma_required?: false,
                abv_upper: 6.2,
                abv_lower: 4.6,
                ibu_upper: 30,
                ibu_lower: 50,
                srm_upper: 18,
                srm_lower: 6)
    Style.create!(name: "Witbier",
                yeast_family: "belgian",
                required_malts: ["white wheat"],
                required_hops: nil,
                common_malts: ["pilsen"],
                common_hops: ["hallertau", "tettnang", "spalt", "saaz"],
                aroma_required?: false,
                abv_upper: 5.5,
                abv_lower: 4.0,
                ibu_upper: 20,
                ibu_lower: 10,
                srm_upper: 6,
                srm_lower: 2)
      Style.create!(name: "Belgian Dubbel",
                yeast_family: "belgian",
                required_malts: ["pilsen"],
                required_hops: nil,
                common_malts: ["special B", "biscuit", "candi sugar"],
                common_hops: ["spalt", "saaz", "east kent goldings", "fuggle"],
                aroma_required?: false,
                abv_upper: 7.6,
                abv_lower: 6.0,
                ibu_upper: 25,
                ibu_lower: 15,
                srm_upper: 18,
                srm_lower: 10)
        Style.create!(name: "Belgian Tripel",
                yeast_family: "belgian",
                required_malts: ["pilsen", "candi sugar"],
                required_hops: nil,
                common_malts: ["biscuit"],
                common_hops: ["spalt", "saaz", "east kent goldings"],
                aroma_required?: false,
                abv_upper: 10.0,
                abv_lower: 7.0,
                ibu_upper: 40,
                ibu_lower: 20,
                srm_upper: 8,
                srm_lower: 4)
          Style.create!(name: "Belgian Dark Strong",
                yeast_family: "belgian",
                required_malts: ["pilsen"],
                required_hops: nil,
                common_malts: ["munich 10", "special B", "candi sugar"],
                common_hops: ["spalt", "saaz", "east kent goldings", "fuggle"],
                aroma_required?: false,
                abv_upper: 12.0,
                abv_lower: 8.0,
                ibu_upper: 35,
                ibu_lower: 20,
                srm_upper: 22,
                srm_lower: 12)
            Style.create!(name: "Saison",
                yeast_family: "saison",
                required_malts: ["pilsen"],
                required_hops: nil,
                common_malts: ["munich 10", "vienna", "white wheat", "candi sugar"],
                common_hops: ["hallertau", "tettnang", "spalt", "saaz", "east kent goldings"],
                aroma_required?: false,
                abv_upper: 7.5,
                abv_lower: 5.0,
                ibu_upper: 35,
                ibu_lower: 20,
                srm_upper: 14,
                srm_lower: 5)
            Style.create!(name: "Kolsch",
                yeast_family: "kolsch",
                required_malts: nil,
                required_hops: nil,
                common_malts: ["pilsen", "white wheat",],
                common_hops: ["hallertau", "tettnang", "spalt", "saaz"],
                aroma_required?: false,
                abv_upper: 5.2,
                abv_lower: 4.4,
                ibu_upper: 30,
                ibu_lower: 20,
                srm_upper: 5,
                srm_lower: 3.5)
end